server:
  port: 8006


spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.112.128
      port: 8500
      discovery:
        service-name: consul-provider-payment
        hostname: 192.168.251.157