server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://192.168.112.128:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: admin
    password: 1234

eureka:
  client:
    register-with-eureka: true  #表示不像注册中心注册自己
    fetch-registry: true #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8002

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.longq.entities  #所有entity别名所在包