server:
  port: 80


spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.112.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 192.168.251.157